### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by mateorico** [Swivelgames/apex-adapt-dark-slim-ui#4]
Hi, nice theme! 
Can i change the color of the lower line in the tab?

Thanks

**Comment by Swivelgames** [comment]
@mateorico What did you have in mind? Currently, because this is an `adapt`, it currently uses the primary color of the current theme.

Did you have an idea on how to improve/change it?

**Comment by mateorico** [comment]
Hi, an option to change the color of emphasis like in Seti-UI 
https://atom.io/themes/seti-ui
Maybe an variable in style.less to do that, could be usefull.

**Comment by Swivelgames** [comment]
@mateorico Great idea! I started to work on a dark, non-adaptive variation of the `apex-ui` theme, but shifted my primary focus on to these two adapt-versions.

This might be a better feature for the `apex-dark-ui` that I started working on.

Please repost this question in that repository so that I can track it properly. I'll start work on finishing the non-adaptive version and I'll add static and custom theming similar to `seti-ui`'s functionality. I think that's a great idea!

[Click here to ask the same question here and I'll see if I can find the time to work on it!](https://github.com/Swivelgames/apex-dark-ui/issues/new)
